server:
  port: 9411
    
eureka:  
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8888}/eureka/

management:
  security:
    enabled: false
