spring:
  application:
    name: gateway-server
server:
  port: 8889
    
# Eureka discovery server configuration
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
endpoints:
  sensitive: false

