info:
  component: Edge Zuul Server

server:
  port: 8765

zuul:
  routes:
      myservice-sdk:
       path: /auto/**
       url: "http://192.168.1.141:8090"
       sensitiveHeaders: none
  add-host-header: true
  prefix : /public
  ignored-services: "*"

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG


spring:
  cloud:
    config:
      uri: http://192.168.1.235:8882
      discovery:
        service-id: configserver
        enabled: true
      profile: prod
      name: gateway-server
