server:
  port: 8882
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 600000

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
