datasource:
  db-notification:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
      test-on-borrow: true
      validation-query: SELECT 1 FROM dual